const API="http://localhost:8080/api"

export const   INVENTARIOSCREADOS_GET_ENDPOINT=API+"/inventarios"
export const   PRODUCTOSCREADOS_GET_ENDPOINT=API+"/productos"
export const   CREARPRODUCTO_POST_ENDPOINT=API+"/productos"
export const   CREARMARCA_POST_ENDPOINT=API+"/marcas"
export const   CREARCATEGORIA_POST_ENDPOINT=API+"/categorias"
export const   CREARUNIDADMEDIDA_POST_ENDPOINT=API+"/unidadesMedidas"
export const   MARCASCREADOS_GET_ENDPOINT=API+"/marcas"
export const   CATEGORIASCREADOS_GET_ENDPOINT=API+"/categorias"
export const   UNIDADESMEDIDASCREADOS_GET_ENDPOINT=API+"/unidadesMedidas"
export const   CREARINVENTARIO_POST_ENDPOINT=API+"/inventarios"
export const   ELIMINARINVENTARIO_DELETE_ENDPOINT=API+"/inventarios"
export const   ELIMINARUNIDADMEDIDA_DELETE_ENDPOINT=API+"/unidadesMedidas"
export const   ELIMINARCATEGORIA_DELETE_ENDPOINT=API+"/categorias"
export const   ELIMINARMARCA_DELETE_ENDPOINT=API+"/marcas"
export const   ELIMINARPRODUCTO_DELETE_ENDPOINT=API+"/productos"